### PR TITLE
Add sliding bar to adjust window width and window center

### PR DESCRIPTION
**Pull request by FjjRichard**
Add sliding bar to adjust window width and window center.When reading medical images, the window width and window center are adaptive according to the modes

### CODE REVIEW

**Comment by geoyee** [comment]
@linhandev 韩哥，我感觉没啥问题，你看看有啥意见

**Comment by linhandev** [comment]
等下我看看，不过感觉我们前端的修改可以等js上了再弄🤔

**Review by linhandev — APPROVED** [review]
LGTM. But we have an upcoming upgrade to js front end. It's better do UI modifications in the new front end

**Review by geoyee — APPROVED** [review]

**Comment by geoyee** [comment]
> 等下我看看，不过感觉我们前端的修改可以等js上了再弄🤔

ok，这个先merge了吧，然后后面的等确定再说

**Pull request merged**
